TRAIN_BATCH: 16
VAL_BATCH : 32
TEST_BATCH : 32
checkpoint_path: ../checkpoint/checkpoint_akutagawa.pth
DEVICE: cuda
EPOCH: 10
LR: 0.001
output_path: ../data/output
test_path: ../data/input/test.csv
train_path: ../data/input/train.csv
MODEL_NAME : 'cl-tohoku/bert-base-japanese-whole-word-masking'
TEXT_COLUMN : 'body'
LABEL_COLUMN : 'author'